# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
commands:
  install-project-dependencies:
    steps:
      - run:
          name: "Install project dependencies"
          command: npm i
  restore-cache:
    steps:
      - restore_cache:
          keys:
            - "npm-packages"

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  build:
    # Specify the execution environment. You can specify an image from Dockerhub or use one of our Convenience Images from CircleCI's Developer Hub.
    # See: https://circleci.com/docs/2.0/configuration-reference/#docker-machine-macos-windows-executor
    docker:
      - image: cimg/node:13.8.0
    steps:
      - checkout
      - install-project-dependencies
      - save_cache:
          key: "npm packages"
          paths:
            - /src/node_modules
      - run:
          name: "Run Linter"
          command: npm run lint
  test:
    docker: cimg/node:13.8.0
    steps:
      - checkout
      - restore-cache
      - install-project-dependencies
      - run:
          name: "Run Tests"
          command: npm run test
  analyse:
    docker: cimg/node:13.8.0
    steps:
      - checkout
      - restore-cache
      - run:
          name: "Run Audit"
          command: npm audit

# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  my-ci-pipeline:
    jobs:
      - build
      - test:
          requires:
            - build
      - analyse:
          requires:
            - test

